### ISSUE TITLE
Lightline and tabbar have black text on black background

### ISSUE THREAD

**Issue by ictinaetus** [huyvohcmc/atlas.vim#2]
## Description of issue
If this is of any importance, I had informed you of some issues with the colours in Neovim being different from what was shown in the screenshots on Reddit earlier today. Since that update, I've noticed that the lightline theme provided apparently has black text on a black background and as a result cannot be seen in almost any of the modes. In visual and insert mode, only the mode is displayed in white text, with what appears to be an additional line showing the same in yellow. The tabbar is, however, just blacked out for the same reasons.

## Screenshots
- "Normal Mode"
![atlas_neovim_errors](https://user-images.githubusercontent.com/32803930/61589220-841ddc80-abc4-11e9-9f61-6150be332332.png)

- "Insert Mode"
![atlas_neovim_errors_2](https://user-images.githubusercontent.com/32803930/61589117-4f5d5580-abc3-11e9-9bfa-8d7d738f1e2d.png)

## Additional info that might be useful:
This was installed on Arch Linux through the community repo [link here](https://www.archlinux.org/packages/community/x86_64/neovim/)
```
nvim --version
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
```
## Suggestions: 
Perhaps gray (`#666666`) text might be a better idea, if over a black bcakground, as in the screenshot on the readme.

**Comment by huyvohcmc** [comment]
Fixed at 12048996d180cbf4ea37c98f4291348dfaafff4d
